return {
	Title = "Happy Life & Family Planning Office",
	Version = "1.0.0.0",
	GameVersion = "1.0.1",
	BackendPlugins = {
		[1] = "HappyLife.dll",
		[2] = "HappyLifeEvent.dll",
	},
	FrontendPlugins = {
		[1] = "HappyLife.Frontend.dll",
	},
	Author = "kkle1994@outlook.com",
	Description = "Have better children, build better families, and skip the cricket nonsense. Please report bugs on Tieba: p/8054902346. Steam does not allow direct links. You can also join QQ group 657760393. This project is open source at: https://github.com/kkle1994/HappyLife",
	Cover = "Cover.jpg",
	Source = 1,
	FileId = 2871634952,
	TagList = {
		[1] = "Extensions",
	},
	SettingGroups = {
		[1] = "Pregnancy",
		[2] = "Social / Marriage",
		[3] = "Taiwu",
		[4] = "Villagers / World",
		[5] = "Combat",
		[6] = "Crickets",
		[7] = "Crafting / Skills",
		[8] = "Construction",
		[9] = "Resources / Shops",
		[10] = "Work",
		[11] = "Other",
		[12] = "Monthly Cooldowns",
	},
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "TaiwuMustPregnant",
			DisplayName = "Taiwu Always Conceives",
			Description = "When enabled, Taiwu or Taiwu's spouse will conceive every time they are intimate.",
			GroupName = "Pregnancy",
			DefaultValue = false,
		},
		[2] = {
			SettingType = "Toggle",
			Key = "NoTaiwuPregnancyLock",
			DisplayName = "No Taiwu Pregnancy Cooldown",
			Description = "Remove Taiwu's pregnancy cooldown.",
			GroupName = "Pregnancy",
			DefaultValue = false,
		},
		[3] = {
			SettingType = "Toggle",
			Key = "TaiwuFertilityMax",
			DisplayName = "Max Taiwu Fertility",
			Description = "When enabled, increases Taiwu's monthly intimacy count.",
			GroupName = "Pregnancy",
			DefaultValue = false,
		},
		[4] = {
			SettingType = "Toggle",
			Key = "BanCricketBorn",
			DisplayName = "No Cricket Births",
			Description = "Never give birth to crickets.",
			GroupName = "Pregnancy",
			DefaultValue = false,
		},
		[5] = {
			SettingType = "Slider",
			Key = "TaiwuChildrenLimit",
			DisplayName = "Taiwu Child Limit",
			Description = "Taiwu's child limit. -1 uses the original game limit. This also limits the guaranteed conception feature.",
			GroupName = "Pregnancy",
			MinValue = -1,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = -1,
		},
		[6] = {
			SettingType = "Slider",
			Key = "TaiwuSpouseChildrenLimit",
			DisplayName = "Taiwu Spouse Child Limit",
			Description = "Child limit for each of Taiwu's spouses. -1 uses the original game limit. This also limits the guaranteed conception feature.",
			GroupName = "Pregnancy",
			MinValue = -1,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = -1,
		},
		[7] = {
			SettingType = "Slider",
			Key = "NpcChildrenLimit",
			DisplayName = "NPC Child Limit",
			Description = "Child limit for NPCs. -1 uses the original game limit. Does not include having children with Taiwu.",
			GroupName = "Pregnancy",
			MinValue = -1,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = -1,
		},
		[8] = {
			SettingType = "Toggle",
			Key = "AllowTaiwuHomoPregnant",
			DisplayName = "Taiwu Same-Sex Pregnancy",
			Description = "Allow same-sex pregnancy involving Taiwu.",
			GroupName = "Pregnancy",
			DefaultValue = false,
		},
		[9] = {
			SettingType = "Dropdown",
			Key = "TaiwuHomoPregnant",
			DisplayName = "Same-Sex Pregnancy Carrier",
			Description = "Choose who becomes pregnant during same-sex intimacy involving Taiwu.",
			GroupName = "Pregnancy",
			Options = {
				[1] = "Random",
				[2] = "Taiwu",
				[3] = "Partner",
			},
			DefaultValue = 0,
		},
		[10] = {
			SettingType = "Toggle",
			Key = "BabyKickable",
			DisplayName = "Babies Can Be Kicked Out",
			Description = "Allow your baby to be kicked out of the party.",
			GroupName = "Pregnancy",
			DefaultValue = false,
		},
		[11] = {
			SettingType = "Toggle",
			Key = "KeepVirgin",
			DisplayName = "Remain Chaste",
			Description = "Intimacy will not affect chastity. It may even restore chastity.",
			GroupName = "Pregnancy",
			DefaultValue = false,
		},
		[12] = {
			SettingType = "Dropdown",
			Key = "TaiwuChildGender",
			DisplayName = "Taiwu Child Sex",
			Description = "Sex of Taiwu's children.",
			GroupName = "Pregnancy",
			Options = {
				[1] = "Random",
				[2] = "Male",
				[3] = "Female",
			},
			DefaultValue = 0,
		},
		[13] = {
			SettingType = "Dropdown",
			Key = "WorldChildGender",
			DisplayName = "Other Child Sex",
			Description = "Sex of other characters' children.",
			GroupName = "Pregnancy",
			Options = {
				[1] = "Random",
				[2] = "Male",
				[3] = "Female",
			},
			DefaultValue = 0,
		},
		[14] = {
			SettingType = "Slider",
			Key = "TaiwuChildQuickGrowAge",
			DisplayName = "Village Children Grow to Age X",
			Description = "In Taiwu Village, children grow one year older each month until age X. Set to 0 to disable.",
			GroupName = "Pregnancy",
			MinValue = 0,
			MaxValue = 14,
			StepSize = 1,
			DefaultValue = 0,
		},
		[15] = {
			SettingType = "Slider",
			Key = "OtherChildQuickGrowAge",
			DisplayName = "Outside Children Grow to Age X",
			Description = "Outside Taiwu Village, children grow one year older each month until age X. Set to 0 to disable.",
			GroupName = "Pregnancy",
			MinValue = 0,
			MaxValue = 14,
			StepSize = 1,
			DefaultValue = 0,
		},
		[16] = {
			SettingType = "Toggle",
			Key = "OnlyExistBloodParents",
			DisplayName = "Show Blood Parents",
			Description = "The parent list will always contain blood parents. Only applies to Taiwu's children.",
			GroupName = "Pregnancy",
			DefaultValue = false,
		},
		[17] = {
			SettingType = "Toggle",
			Key = "BanAddStepChildren",
			DisplayName = "No Stepchildren",
			Description = "Disable adding stepchildren. Only applies to Taiwu.",
			GroupName = "Pregnancy",
			DefaultValue = false,
		},
		[18] = {
			SettingType = "Slider",
			Key = "FavorabilityMultiple",
			DisplayName = "Favor Gain Multiplier",
			Description = "Increase the rate at which favorability rises between all characters. A world full of love.",
			GroupName = "Social / Marriage",
			MinValue = 1,
			MaxValue = 100,
			StepSize = 1,
			DefaultValue = 1,
		},
		[19] = {
			SettingType = "Toggle",
			Key = "UnlimitedInformation",
			DisplayName = "Unlimited Messages",
			Description = "Use information/messages without a limit.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[20] = {
			SettingType = "Toggle",
			Key = "UnlimitedGroupMemberCount",
			DisplayName = "Unlimited Companions",
			Description = "Unlimited companion count.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[21] = {
			SettingType = "Toggle",
			Key = "UnlimitedSworn",
			DisplayName = "Unlimited Sworn Siblings",
			Description = "Unlimited sworn sibling count.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[22] = {
			SettingType = "Toggle",
			Key = "UnlimitedMarry",
			DisplayName = "Unlimited Spouses",
			Description = "Do not limit your number of spouses.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[23] = {
			SettingType = "Toggle",
			Key = "UnlimitedConfess",
			DisplayName = "Confess to Anyone",
			Description = "Allow confession to anyone.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[24] = {
			SettingType = "Toggle",
			Key = "FixConfessIssue",
			DisplayName = "Fix Confession Formula",
			Description = "Remove same-sex restrictions and fix penalties caused by Taiwu's children or spouses.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[25] = {
			SettingType = "Toggle",
			Key = "BanNTRTaiwu",
			DisplayName = "Strictly Protect Taiwu's Partners",
			Description = "All NPC confessions to people in a romantic relationship with Taiwu will fail, and the reverse also applies.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[26] = {
			SettingType = "Toggle",
			Key = "AllowSetUpAnyTeammate",
			DisplayName = "Matchmake Anyone",
			Description = "The matchmaking event can introduce any available teammate to anyone, even your spouse to your spouse.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[27] = {
			SettingType = "Toggle",
			Key = "FightForMarryWithMarried",
			DisplayName = "Events Ignore Marriage",
			Description = "Events such as martial contests for marriage ignore existing marriages.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[28] = {
			SettingType = "Toggle",
			Key = "MarryAdventrueIgnoreMarried",
			DisplayName = "Marriage Adventures Ignore Marriage",
			Description = "Marriage adventures ignore existing marriages.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[29] = {
			SettingType = "Toggle",
			Key = "BanFavorDebt",
			DisplayName = "No Favor Debt",
			Description = "Prevent new favor debt from being created. Existing favor debt cannot be removed by this setting.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[30] = {
			SettingType = "Toggle",
			Key = "RemoveSupportCost",
			DisplayName = "Remove Some Support Costs",
			Description = "Remove local favor and experience costs, but the requirements must still be met.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[31] = {
			SettingType = "Toggle",
			Key = "SeverAndDivorce",
			DisplayName = "Betrayal Divorce",
			Description = "Sever the relationship and divorce at the same time, if married.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[32] = {
			SettingType = "Toggle",
			Key = "CancelMonthlyEventFavorReduce",
			DisplayName = "No Monthly Favor Loss",
			Description = "Set favorability losses from monthly events, arts, and rumors/secrets to 0.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[33] = {
			SettingType = "Toggle",
			Key = "CancelMonthlyEventHappinessReduce",
			DisplayName = "No Monthly Mood Loss",
			Description = "Prevent mood reductions from monthly events for Taiwu's spouses and lovers, including unmarried partners.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[34] = {
			SettingType = "Toggle",
			Key = "NoImmoralFameActions",
			DisplayName = "No Immoral Reputation",
			Description = "Remove reputation losses from bullying children, scandalous behavior, violating kinship norms, and making low-reputation lovers.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[35] = {
			SettingType = "Toggle",
			Key = "BanEventSpendPrestige",
			DisplayName = "No Favor-Debt Events",
			Description = "Remove monthly events for merchant praise and extending favors.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[36] = {
			SettingType = "Toggle",
			Key = "BanTaiwuInfected",
			DisplayName = "No Taiwu Corruption",
			Description = "Prevent Taiwu from becoming Xiangshu-corrupted.",
			GroupName = "Taiwu",
			DefaultValue = false,
		},
		[37] = {
			SettingType = "Toggle",
			Key = "TaiwuNeverDie",
			DisplayName = "Taiwu Does Not Lose Health",
			Description = "Taiwu will not lose health.",
			GroupName = "Taiwu",
			DefaultValue = false,
		},
		[38] = {
			SettingType = "Toggle",
			Key = "ShopTaiwuAgeIncreasing",
			DisplayName = "Stop Taiwu Aging",
			Description = "Stop Taiwu from aging.",
			GroupName = "Taiwu",
			DefaultValue = false,
		},
		[39] = {
			SettingType = "Toggle",
			Key = "AutoAddTaiwuGoodFeatures",
			DisplayName = "Auto-Add Good Taiwu Traits",
			Description = "Automatically add traits such as Dreamworld Person when creating Taiwu. Also triggers on succession.",
			GroupName = "Taiwu",
			DefaultValue = false,
		},
		[40] = {
			SettingType = "Toggle",
			Key = "RemoveTaiwuBadFeatures",
			DisplayName = "Remove Bad Traits on Creation",
			Description = "Remove bad traits when creating a character. Also triggers on succession, including traits such as Xiangshu Corruption.",
			GroupName = "Taiwu",
			DefaultValue = false,
		},
		[41] = {
			SettingType = "Toggle",
			Key = "LockTaiwuSkillLateSuccess",
			DisplayName = "Set Character to Late Bloomer",
			Description = "Craft, martial, and other attainments are set to late bloomer. Also triggers on succession.",
			GroupName = "Taiwu",
			DefaultValue = false,
		},
		[42] = {
			SettingType = "Toggle",
			Key = "LockDaysInMonth",
			DisplayName = "Lock Time",
			Description = "When enabled, time only decreases through active spending.",
			GroupName = "Taiwu",
			DefaultValue = true,
		},
		[43] = {
			SettingType = "Toggle",
			Key = "BanTaiwuVillagerInfected",
			DisplayName = "No Villager Corruption",
			Description = "Prevent Taiwu Village residents from becoming Xiangshu-corrupted.",
			GroupName = "Villagers / World",
			DefaultValue = false,
		},
		[44] = {
			SettingType = "Slider",
			Key = "InfectedSpeedRate",
			DisplayName = "World Corruption Speed",
			Description = "Xiangshu corruption speed worldwide. 100% is the original speed. Higher is faster, and negative values can reduce corruption, but cannot reverse characters who are already corrupted.",
			GroupName = "Villagers / World",
			MinValue = -100,
			MaxValue = 500,
			StepSize = 1,
			DefaultValue = 100,
		},
		[45] = {
			SettingType = "Toggle",
			Key = "TaiwuValligerNoQiDisorder",
			DisplayName = "No Villager Qi Disorder",
			Description = "Improve recovery from qi disorder for villagers.",
			GroupName = "Villagers / World",
			DefaultValue = false,
		},
		[46] = {
			SettingType = "Toggle",
			Key = "VillagersNeverDie",
			DisplayName = "Villagers Do Not Lose Health",
			Description = "Villagers will not lose health.",
			GroupName = "Villagers / World",
			DefaultValue = false,
		},
		[47] = {
			SettingType = "Dropdown",
			Key = "WorldCreatePeopleSex",
			DisplayName = "Initial World Sex",
			Description = "Override the initial sex of everyone in a new world.",
			GroupName = "Villagers / World",
			Options = {
				[1] = "Random",
				[2] = "Male",
				[3] = "Female",
			},
			DefaultValue = 0,
		},
		[48] = {
			SettingType = "Dropdown",
			Key = "VillagerRecrultSex",
			DisplayName = "Recruit Sex",
			Description = "Override the recruit sex for all of your recruitment buildings.",
			GroupName = "Villagers / World",
			Options = {
				[1] = "Random",
				[2] = "Male",
				[3] = "Female",
			},
			DefaultValue = 0,
		},
		[49] = {
			SettingType = "Dropdown",
			Key = "VillagerRecrultAppearanceLowerLimit",
			DisplayName = "Recruit Appearance Minimum",
			Description = "Minimum appearance level for recruited villagers.",
			GroupName = "Villagers / World",
			Options = {
				[1] = "Random",
				[2] = "Ordinary",
				[3] = "Outstanding",
				[4] = "Jade",
				[5] = "Elegant",
				[6] = "Transcendent",
				[7] = "Celestial",
			},
			DefaultValue = 0,
		},
		[50] = {
			SettingType = "Dropdown",
			Key = "VillagerRecrultMorality",
			DisplayName = "Recruit Moral Stance",
			Description = "Default moral stance for recruited villagers.",
			GroupName = "Villagers / World",
			Options = {
				[1] = "Random",
				[2] = "Self-Centered",
				[3] = "Rebellious",
				[4] = "Neutral",
				[5] = "Kind",
				[6] = "Upright",
			},
			DefaultValue = 0,
		},
		[51] = {
			SettingType = "Toggle",
			Key = "AllowAllGenderInOrganization",
			DisplayName = "All Sexes in Sects",
			Description = "Any sect can have both men and women, without affecting promotion.",
			GroupName = "Villagers / World",
			DefaultValue = false,
		},
		[52] = {
			SettingType = "Toggle",
			Key = "CleanTaiwuDarkDash",
			DisplayName = "Clear Villagers' Dark Ash",
			Description = "Clear all Dark Ash from Taiwu villagers during the monthly transition.",
			GroupName = "Villagers / World",
			DefaultValue = false,
		},
		[53] = {
			SettingType = "Toggle",
			Key = "CleanOthersDarkDash",
			DisplayName = "Clear Others' Dark Ash",
			Description = "Clear all Dark Ash from everyone outside the village during the monthly transition.",
			GroupName = "Villagers / World",
			DefaultValue = false,
		},
		[54] = {
			SettingType = "Toggle",
			Key = "ShowKidCharm",
			DisplayName = "Show Child Charm",
			Description = "Show child charm.",
			GroupName = "Villagers / World",
			DefaultValue = false,
		},
		[55] = {
			SettingType = "Toggle",
			Key = "ShowMaskCharm",
			DisplayName = "Show Masked Charm",
			Description = "Show charm even when the face is covered, such as with Jieqing clothing.",
			GroupName = "Villagers / World",
			DefaultValue = false,
		},
		[56] = {
			SettingType = "Slider",
			Key = "TaiwuRecoverPercent",
			DisplayName = "Taiwu Recovery %",
			Description = "Taiwu's health recovery speed in combat.",
			GroupName = "Combat",
			MinValue = 0,
			MaxValue = 500,
			StepSize = 1,
			DefaultValue = 100,
		},
		[57] = {
			SettingType = "Slider",
			Key = "EnemyRecoverPercent",
			DisplayName = "Enemy Recovery %",
			Description = "Enemy health recovery speed in combat.",
			GroupName = "Combat",
			MinValue = 0,
			MaxValue = 500,
			StepSize = 1,
			DefaultValue = 100,
		},
		[58] = {
			SettingType = "Slider",
			Key = "WeaponDurabilityRate",
			DisplayName = "Weapon Wear Chance",
			Description = "Chance for weapons to lose durability, from 1% to 100%. 0% means no durability loss.",
			GroupName = "Combat",
			MinValue = 0,
			MaxValue = 100,
			StepSize = 1,
			DefaultValue = 100,
		},
		[59] = {
			SettingType = "Toggle",
			Key = "SameConsummateLevel",
			DisplayName = "Same Purity Worldwide",
			Description = "Set the same purity realm level for the whole world.",
			GroupName = "Combat",
			DefaultValue = false,
		},
		[60] = {
			SettingType = "Slider",
			Key = "SameConsummateLevelValue",
			DisplayName = "World Purity Level",
			Description = "Purity realm level for the whole world. Requires Same Purity Worldwide to be enabled first.",
			GroupName = "Combat",
			MinValue = 0,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = 0,
		},
		[61] = {
			SettingType = "Toggle",
			Key = "HideKillRuMoRenOption",
			DisplayName = "Hide Xiangshu Kill Option",
			Description = "Hide the option to kill Xiangshu when fleeing after losing to a corrupted person.",
			GroupName = "Combat",
			DefaultValue = false,
		},
		[62] = {
			SettingType = "Dropdown",
			Key = "CombatDiffcultyOverwrite",
			DisplayName = "Override Combat Difficulty",
			Description = "Override the combat difficulty of your current save without modifying save data.",
			GroupName = "Combat",
			Options = {
				[1] = "Off",
				[2] = "Easy",
				[3] = "Normal",
				[4] = "Hard",
				[5] = "Extreme",
			},
			DefaultValue = 0,
		},
		[63] = {
			SettingType = "Toggle",
			Key = "EnableUnlimitedCricketBattle",
			DisplayName = "No Monthly Cricket Duel Limit",
			Description = "Cricket duels are not limited per month.",
			GroupName = "Crickets",
			DefaultValue = false,
		},
		[64] = {
			SettingType = "Toggle",
			Key = "CricketDuelNoDurabilityLoss",
			DisplayName = "No Cricket Duel Durability Loss",
			Description = "Cricket duels will not reduce cricket durability, and all injuries are healed after battle.",
			GroupName = "Crickets",
			DefaultValue = false,
		},
		[65] = {
			SettingType = "Toggle",
			Key = "UnlimitedReferenceBookSlot",
			DisplayName = "Unlock Reference Book Slots",
			Description = "Unlock reference book slots.",
			GroupName = "Crafting / Skills",
			DefaultValue = false,
		},
		[66] = {
			SettingType = "Toggle",
			Key = "RestoreAttainmentPerGrade",
			DisplayName = "Improve Attainment Bonus",
			Description = "Restore the attainment bonus cap to 270%.",
			GroupName = "Crafting / Skills",
			DefaultValue = false,
		},
		[67] = {
			SettingType = "Toggle",
			Key = "GrowAbilitiesWithLoopingNeigong",
			DisplayName = "Internal Arts Raise Attributes",
			Description = "Running internal arts such as Bright Lion Strength or Sunyue Method can increase attributes. It must be actively running in the lower-left slot, not merely equipped. Adds 1 point each month.",
			GroupName = "Crafting / Skills",
			DefaultValue = false,
		},
		[68] = {
			SettingType = "Toggle",
			Key = "GrowQualificationsWithReadingBook",
			DisplayName = "Grade-9 Books Raise Aptitude",
			Description = "Reading grade-9 books can increase the corresponding aptitude by 1 point each month.",
			GroupName = "Crafting / Skills",
			DefaultValue = false,
		},
		[69] = {
			SettingType = "Toggle",
			Key = "MakeItemImmediately",
			DisplayName = "Instant Item Crafting",
			Description = "Craft items instantly.",
			GroupName = "Crafting / Skills",
			DefaultValue = false,
		},
		[70] = {
			SettingType = "Slider",
			Key = "IncreaseBuildingMaxCount",
			DisplayName = "Increase Building Limit",
			Description = "Increase the maximum number of buildings that can be built in Taiwu Village.",
			GroupName = "Construction",
			MinValue = 0,
			MaxValue = 200,
			StepSize = 1,
			DefaultValue = 0,
		},
		[71] = {
			SettingType = "Toggle",
			Key = "EnableBuildResource",
			DisplayName = "Build Resources (Restart)",
			Description = "Allow construction of natural resources. Takes effect after restarting.",
			GroupName = "Construction",
			DefaultValue = false,
		},
		[72] = {
			SettingType = "Toggle",
			Key = "NoDependentBuilding",
			DisplayName = "Ignore Dependencies (Restart)",
			Description = "Ignore dependent buildings when building. Requires Build Resources to be enabled first. Takes effect after restarting.",
			GroupName = "Construction",
			DefaultValue = false,
		},
		[73] = {
			SettingType = "Toggle",
			Key = "NoResourceBuildingCoreItem",
			DisplayName = "Ignore Resource Core Materials (Restart)",
			Description = "Ignore core materials when building resources. Requires Build Resources to be enabled first. Takes effect after restarting.",
			GroupName = "Construction",
			DefaultValue = false,
		},
		[74] = {
			SettingType = "Toggle",
			Key = "FreePlanBuilding",
			DisplayName = "Free Planned Building Moves",
			Description = "Moving buildings during planning costs no resources.",
			GroupName = "Construction",
			DefaultValue = false,
		},
		[75] = {
			SettingType = "Slider",
			Key = "AddResourceMultiple",
			DisplayName = "Resource Gain Multiplier",
			Description = "Taiwu's resource gain multiplier.",
			GroupName = "Resources / Shops",
			MinValue = 1,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = 1,
		},
		[76] = {
			SettingType = "Toggle",
			Key = "ResourceMultipleOnlyForMonthlyIncreasing",
			DisplayName = "Only Monthly Resources",
			Description = "Taiwu's resource gain multiplier only applies to resources gained during the current month.",
			GroupName = "Resources / Shops",
			DefaultValue = true,
		},
		[77] = {
			SettingType = "Toggle",
			Key = "UnlimitedMerchantFavorability",
			DisplayName = "Max Merchant Favor",
			Description = "Set merchant favorability directly to 6000.",
			GroupName = "Resources / Shops",
			DefaultValue = false,
		},
		[78] = {
			SettingType = "Toggle",
			Key = "EnemyNestDefaultIncome",
			DisplayName = "Default Nest Income",
			Description = "Unimplemented nests gain default prestige income of 1000-2000. The fitted random values follow a normal distribution.",
			GroupName = "Resources / Shops",
			DefaultValue = false,
		},
		[79] = {
			SettingType = "Slider",
			Key = "ImproveSkillWithWorkPossibility",
			DisplayName = "Work Skill-Gain Chance",
			Description = "Work can improve skill aptitudes. Each month has the chance you set here. Escort agencies and similar jobs randomly improve one combat skill aptitude.",
			GroupName = "Work",
			MinValue = 0,
			MaxValue = 100,
			StepSize = 1,
			DefaultValue = 0,
		},
		[80] = {
			SettingType = "Slider",
			Key = "ImproveSkillWithWorkLimited",
			DisplayName = "Work Skill-Gain Cap",
			Description = "Upper limit for skill aptitude gains from work.",
			GroupName = "Work",
			MinValue = 50,
			MaxValue = 200,
			StepSize = 1,
			DefaultValue = 90,
		},
		[81] = {
			SettingType = "Slider",
			Key = "MaxSaveBackupCount",
			DisplayName = "Save Backup Count",
			Description = "Maximum number of save backups. -1 disables backups. Do not ask why the maximum is only 127; the save count uses sbyte.",
			GroupName = "Other",
			MinValue = -1,
			MaxValue = 127,
			StepSize = 1,
			DefaultValue = 3,
		},
		[82] = {
			SettingType = "Toggle",
			Key = "UnlimitApprovingRateUpperLimit",
			DisplayName = "Unlock Sect Support",
			Description = "Sect support limit.",
			GroupName = "Other",
			DefaultValue = false,
		},
		[83] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_0",
			DisplayName = "No Monthly Cooldown: Chat About News",
			Description = "Chat About News has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[84] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_3",
			DisplayName = "No Monthly Cooldown: Praise",
			Description = "Praise has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[85] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_7",
			DisplayName = "No Monthly Cooldown: Cricket Duel",
			Description = "Cricket duels have no monthly use limit. Equivalent to the switch in the Crickets group.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[86] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_8",
			DisplayName = "No Monthly Cooldown: Art Contest",
			Description = "Art contests have no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[87] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_9",
			DisplayName = "No Monthly Cooldown: Martial Sparring",
			Description = "Martial sparring has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[88] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_61",
			DisplayName = "No Monthly Cooldown: Donate Silver",
			Description = "Donating silver has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[89] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_80",
			DisplayName = "No Monthly Cooldown: Prefecture Regulations",
			Description = "Prefecture Regulations has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[90] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_81",
			DisplayName = "No Monthly Cooldown: Costly Treatment",
			Description = "Costly Treatment has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[91] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_100",
			DisplayName = "No Monthly Cooldown: Lion-Phase Farce",
			Description = "Lion-Phase Farce has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[92] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_111",
			DisplayName = "No Monthly Cooldown: Persuade Captive",
			Description = "Persuading captives has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[93] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_112",
			DisplayName = "No Monthly Cooldown: Pay Respects to the Deceased",
			Description = "Paying respects to the deceased has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[94] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_128",
			DisplayName = "No Monthly Cooldown: Extend Favors",
			Description = "Extending favors has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[95] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_129",
			DisplayName = "No Monthly Cooldown: Matchmaking",
			Description = "Matchmaking has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[96] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_130",
			DisplayName = "No Monthly Cooldown: Stabilize Culture",
			Description = "Stabilize Culture has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[97] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_131",
			DisplayName = "No Monthly Cooldown: Poetry and Painting",
			Description = "Poetry and Painting has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[98] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_132",
			DisplayName = "No Monthly Cooldown: Merchant Guild Praise",
			Description = "Merchant Guild Praise has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[99] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_133",
			DisplayName = "No Monthly Cooldown: Tend the Land",
			Description = "Tending the land has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[100] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_134",
			DisplayName = "No Monthly Cooldown: Marketplace Life",
			Description = "Marketplace Life has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[101] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_135",
			DisplayName = "No Monthly Cooldown: Exchange Tools",
			Description = "Exchanging tools has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[102] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_136",
			DisplayName = "No Monthly Cooldown: Strip Star Fortune",
			Description = "Stripping star fortune has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[103] = {
			SettingType = "Toggle",
			Key = "MonthlyCooldown_139",
			DisplayName = "No Monthly Cooldown: Groom NPC",
			Description = "Grooming NPCs has no monthly use limit.",
			GroupName = "Monthly Cooldowns",
			DefaultValue = false,
		},
		[104] = {
			SettingType = "Toggle",
			Key = "EnableQuickSaveLoad",
			DisplayName = "Quick Save / Load",
			Description = "When enabled, you can use the F4 menu, F5 quick save, and F8 quick load. Requires restarting the game.",
			GroupName = "Other",
			DefaultValue = false,
		},
		[105] = {
			SettingType = "Toggle",
			Key = "DirectInviteToVillage",
			DisplayName = "Directly Invite Companions / Villagers",
			Description = "When enabled, NPC dialogue directly shows the Recruit as Companion and Invite to Village options without favorability requirements. The game's original resource and other requirements still apply.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
		[106] = {
			SettingType = "Toggle",
			Key = "IgnoreInviteIdentityCheck",
			DisplayName = "Ignore Invite Identity Limits",
			Description = "When enabled, recruiting as a companion and inviting back to the village ignore identity rank, alertness, and other identity restrictions, so any NPC can be invited successfully. Note: Sword Tomb bosses, Xiangshu minions, and other special NPCs may still be limited by other mechanics.",
			GroupName = "Social / Marriage",
			DefaultValue = false,
		},
	},
	Visibility = 0,
	UpdateLogList = {
		[1] = {
			Timestamp = 1750791320,
			LogList = {
				[1] = "Resubmitted the config file",
			},
		},
		[2] = {
			Timestamp = 1750791849,
			LogList = {
				[1] = "Updated the mod name",
			},
		},
		[3] = {
			Timestamp = 1750864160,
			LogList = {
				[1] = "Fixed the IL error issue",
			},
		},
		[4] = {
			Timestamp = 1751395200,
			LogList = {
				[1] = "Organized menu items into groups: Pregnancy, Social / Marriage, Taiwu, Villagers / World, Combat, Crickets, Crafting / Skills, Construction, Resources / Shops, Work, and Other",
			},
		},
		[5] = {
			Timestamp = 1781693747,
		},
		[6] = {
			Timestamp = 1781694813,
		},
	},
	ChangeConfig = false,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
	WorkshopCover = "Cover.jpg",
}