return {
	Title = "Happy Life & Family Planning Office",
	Version = "1.0",
	GameVersion = "0.0.74.37",
	BackendPlugins = {"HappyLife.dll", "HappyLifeEvent.dll"},
	FrontendPlugins = {"HappyLife.Frontend.dll"},
	Author = "kkle1994@outlook.com",
	Description = "Have better children, build better families, and skip the cricket nonsense. Please report bugs on Tieba: p/8054902346, or join QQ group 657760393. This project is open source at: https://github.com/kkle1994/HappyLife",
	Cover = "Cover.jpg",
	Source = 1,
	FileId = 2871634952,
	TagList = {"Extensions"},
	DefaultSettings = {
		{Key="BanCricketBorn", DisplayName="No Cricket Births", Description="Never give birth to crickets.", SettingType="Toggle", DefaultValue=false},
		{Key="TaiwuRecoverPercent", DisplayName="Taiwu Recovery %", Description="Taiwu's health recovery speed in combat.", SettingType="Slider", DefaultValue=100, MinValue=0, MaxValue=500},
		{Key="EnemyRecoverPercent", DisplayName="Enemy Recovery %", Description="Enemy health recovery speed in combat.", SettingType="Slider", DefaultValue=100, MinValue=0, MaxValue=500},
		{Key="WeaponDurabilityRate", DisplayName="Weapon Wear Chance", Description="Chance for weapons to lose durability, from 1% to 100%. 0% means no durability loss.", SettingType="Slider", DefaultValue=100, MinValue=0, MaxValue=100},
		{Key="IncreaseBuildingMaxCount", DisplayName="Increase Building Limit", Description="Increase the maximum number of buildings that can be built in Taiwu Village.", SettingType="Slider", DefaultValue=0, MinValue=0, MaxValue=200},
		{Key="FavorabilityMultiple", DisplayName="Favor Gain Multiplier", Description="Increase the rate at which favorability rises between all characters. A world full of love.", SettingType="Slider", DefaultValue=1, MinValue=1, MaxValue=100},
		{Key="UnlimitedInformation", DisplayName="Unlimited Messages", Description="Use information/messages without a limit.", SettingType="Toggle", DefaultValue=false},
		{Key="BanTaiwuInfected", DisplayName="No Taiwu Corruption", Description="Prevent Taiwu from becoming Xiangshu-corrupted.", SettingType="Toggle", DefaultValue=false},
		{Key="BanTaiwuVillagerInfected", DisplayName="No Villager Corruption", Description="Prevent Taiwu Village residents from becoming Xiangshu-corrupted.", SettingType="Toggle", DefaultValue=false},
		{Key="InfectedSpeedRate", DisplayName="World Corruption Speed", Description="Xiangshu corruption speed worldwide. 100% is the original speed. Higher is faster, and negative values can reduce corruption, but cannot reverse characters who are already corrupted.", SettingType="Slider", DefaultValue=100, MinValue=-100, MaxValue=500},
		{Key="AddResourceMultiple", DisplayName="Resource Gain Multiplier", Description="Taiwu's resource gain multiplier.", SettingType="Slider", DefaultValue=1, MinValue=1, MaxValue=20},
		{Key="ResourceMultipleOnlyForMonthlyIncreasing", DisplayName="Only Monthly Resources", Description="Taiwu's resource gain multiplier only applies to resources gained during the current month.", SettingType="Toggle", DefaultValue=true},
		{Key="UnlimitedMerchantFavorability", DisplayName="Max Merchant Favor", Description="Set merchant favorability directly to 6000.", SettingType="Toggle", DefaultValue=false},
		-- {Key="HighLevelShop", DisplayName="Unlock High-Level Goods", Description="Sell high-level goods.", SettingType="Toggle", DefaultValue=false},
		{Key="MaxSaveBackupCount", DisplayName="Save Backup Count", Description="Maximum number of save backups. -1 disables backups. Do not ask why the maximum is only 127; the save count uses sbyte.", SettingType="Slider", DefaultValue=3, MinValue=-1, MaxValue=127},
		{Key="TaiwuValligerNoQiDisorder", DisplayName="No Villager Qi Disorder", Description="Improve recovery from qi disorder for villagers.", SettingType="Toggle", DefaultValue=false},
		{Key="UnlimitApprovingRateUpperLimit", DisplayName="Unlock Sect Support", Description="Sect support limit.", SettingType="Toggle", DefaultValue=false},
		{Key="VillagersNeverDie", DisplayName="Villagers Do Not Lose Health", Description="Villagers will not lose health.", SettingType="Toggle", DefaultValue=false},
		{Key="TaiwuNeverDie", DisplayName="Taiwu Does Not Lose Health", Description="Taiwu will not lose health.", SettingType="Toggle", DefaultValue=false},
		{Key="SameConsummateLevel", DisplayName="Same Purity Worldwide", Description="Set the same purity realm level for the whole world.", SettingType="Toggle", DefaultValue=false},
		{Key="SameConsummateLevelValue", DisplayName="World Purity Level", Description="Purity realm level for the whole world. Requires Same Purity Worldwide to be enabled first.", SettingType="Slider", DefaultValue=0, MinValue=0, MaxValue=20},
		{Key="TaiwuMustPregnant", DisplayName="Taiwu Always Conceives", Description="When enabled, Taiwu or Taiwu's spouse will conceive every time they are intimate.", SettingType="Toggle", DefaultValue=false},
		{Key="NoTaiwuPregnancyLock", DisplayName="No Taiwu Pregnancy Cooldown", Description="Remove Taiwu's pregnancy cooldown.", SettingType="Toggle", DefaultValue=false},
		{Key="TaiwuFertilityMax", DisplayName="Max Taiwu Fertility", Description="When enabled, increases Taiwu's monthly intimacy count.", SettingType="Toggle", DefaultValue=false},
		{Key="TaiwuChildrenLimit", DisplayName="Taiwu Child Limit", Description="Taiwu's child limit. -1 uses the original game limit. This also limits the guaranteed conception feature.", SettingType="Slider", DefaultValue=-1, MinValue=-1, MaxValue=20},
		{Key="TaiwuSpouseChildrenLimit", DisplayName="Taiwu Spouse Child Limit", Description="Child limit for each of Taiwu's spouses. -1 uses the original game limit. This also limits the guaranteed conception feature.", SettingType="Slider", DefaultValue=-1, MinValue=-1, MaxValue=20},
		{Key="NpcChildrenLimit", DisplayName="NPC Child Limit", Description="Child limit for NPCs. -1 uses the original game limit. Does not include having children with Taiwu.", SettingType="Slider", DefaultValue=-1, MinValue=-1, MaxValue=20},
		{Key="ShopTaiwuAgeIncreasing", DisplayName="Stop Taiwu Aging", Description="Stop Taiwu from aging.", SettingType="Toggle", DefaultValue=false},
		{Key="UnlimitedGroupMemberCount", DisplayName="Unlimited Companions", Description="Unlimited companion count.", SettingType="Toggle", DefaultValue=false},
		{Key="UnlimitedSworn", DisplayName="Unlimited Sworn Siblings", Description="Unlimited sworn sibling count.", SettingType="Toggle", DefaultValue=false},
		{Key="UnlimitedMarry", DisplayName="Unlimited Spouses", Description="Do not limit your number of spouses.", SettingType="Toggle", DefaultValue=false},
		{Key="UnlimitedConfess", DisplayName="Confess to Anyone", Description="Allow confession to anyone.", SettingType="Toggle", DefaultValue=false},
		{Key="ShowKidCharm", DisplayName="Show Child Charm", Description="Show child charm.", SettingType="Toggle", DefaultValue=false},
		{Key="ShowMaskCharm", DisplayName="Show Masked Charm", Description="Show charm even when the face is covered, such as with Jieqing clothing.", SettingType="Toggle", DefaultValue=false},
		{Key="EnableBuildResource", DisplayName="Build Resources (Restart)", Description="Allow construction of natural resources. Takes effect after restarting.", SettingType="Toggle", DefaultValue=false},
		{Key="NoDependentBuilding", DisplayName="Ignore Dependencies (Restart)", Description="Ignore dependent buildings when building. Requires Build Resources to be enabled first. Takes effect after restarting.", SettingType="Toggle", DefaultValue=false},
		{Key="FixConfessIssue", DisplayName="Fix Confession Formula", Description="Remove same-sex restrictions and fix penalties caused by Taiwu's children or spouses.", SettingType="Toggle", DefaultValue=false},
		{Key="AllowTaiwuHomoPregnant", DisplayName="Taiwu Same-Sex Pregnancy", Description="Allow same-sex pregnancy involving Taiwu.", SettingType="Toggle", DefaultValue=false},
		{Key="TaiwuHomoPregnant", DisplayName="Same-Sex Pregnancy Carrier", Description="Choose who becomes pregnant during same-sex intimacy involving Taiwu.", SettingType="Dropdown", Options={ "Random", "Taiwu", "Partner"}, DefaultValue=0},
		{Key="BanNTRTaiwu", DisplayName="Strictly Protect Taiwu's Partners", Description="All NPC confessions to people in a romantic relationship with Taiwu will fail, and the reverse also applies.", SettingType="Toggle", DefaultValue=false},
		{Key="HideKillRuMoRenOption", DisplayName="Hide Xiangshu Kill Option", Description="Hide the option to kill Xiangshu when fleeing after losing to a corrupted person.", SettingType="Toggle", DefaultValue=false},
		{Key="BabyKickable", DisplayName="Babies Can Be Kicked Out", Description="Allow your baby to be kicked out of the party.", SettingType="Toggle", DefaultValue=false},
		{Key="FightForMarryWithMarried", DisplayName="Events Ignore Marriage", Description="Events such as martial contests for marriage ignore existing marriages.", SettingType="Toggle", DefaultValue=false},
		{Key="KeepVirgin", DisplayName="Remain Chaste", Description="Intimacy will not affect chastity. It may even restore chastity.", SettingType="Toggle", DefaultValue=false},
		{Key="CombatDiffcultyOverwrite", DisplayName="Override Combat Difficulty", Description="Override the combat difficulty of your current save without modifying save data.", SettingType="Dropdown", Options={ "Off", "Easy", "Normal","Hard", "Extreme" }, DefaultValue=0},
		{Key="CancelMonthlyEventFavorReduce", DisplayName="No Monthly Favor Loss", Description="Set favorability losses from monthly events, arts, and rumors/secrets to 0.", SettingType="Toggle", DefaultValue=false},
		{Key="CancelMonthlyEventHappinessReduce", DisplayName="No Monthly Mood Loss", Description="Prevent mood reductions from monthly events for Taiwu's spouses and lovers, including unmarried partners.", SettingType="Toggle", DefaultValue=false},
		{Key="NoImmoralFameActions", DisplayName="No Immoral Reputation", Description="Remove reputation losses from bullying children, scandalous behavior, violating kinship norms, and making low-reputation lovers.", SettingType="Toggle", DefaultValue=false},
		{Key="BanEventSpendPrestige", DisplayName="No Favor-Debt Events", Description="Remove monthly events for merchant praise and extending favors.", SettingType="Toggle", DefaultValue=false},
		{Key="EnemyNestDefaultIncome", DisplayName="Default Nest Income", Description="Unimplemented nests gain default prestige income of 1000-2000. The fitted random values follow a normal distribution.", SettingType="Toggle", DefaultValue=false},
		{Key="AllowSetUpAnyTeammate", DisplayName="Matchmake Anyone", Description="The matchmaking event can introduce any available teammate to anyone, even your spouse to your spouse.", SettingType="Toggle", DefaultValue=false},
		{Key="ImproveSkillWithWorkPossibility", DisplayName="Work Skill-Gain Chance", Description="Work can improve skill aptitudes. Each month has the chance you set here. Escort agencies and similar jobs randomly improve one combat skill aptitude.", SettingType="Slider", DefaultValue=0, MinValue=0, MaxValue=100},
		{Key="ImproveSkillWithWorkLimited", DisplayName="Work Skill-Gain Cap", Description="Upper limit for skill aptitude gains from work.", SettingType="Slider", DefaultValue=90, MinValue=50, MaxValue=200},
		{Key="WorldCreatePeopleSex", DisplayName="Initial World Sex", Description="Override the initial sex of everyone in a new world.", SettingType="Dropdown", Options={ "Random", "Male", "Female"}, DefaultValue=0},
		{Key="VillagerRecrultSex", DisplayName="Recruit Sex", Description="Override the recruit sex for all of your recruitment buildings.", SettingType="Dropdown", Options={ "Random", "Male", "Female"}, DefaultValue=0},
		{Key="VillagerRecrultAppearanceLowerLimit", DisplayName="Recruit Appearance Minimum", Description="Minimum appearance level for recruited villagers.", SettingType="Dropdown", Options={ "Random", "Ordinary", "Outstanding", "Jade", "Elegant", "Transcendent", "Celestial" }, DefaultValue=0},
		{Key="VillagerRecrultMorality", DisplayName="Recruit Moral Stance", Description="Default moral stance for recruited villagers.", SettingType="Dropdown", Options={ "Random", "Self-Centered", "Rebellious", "Neutral", "Kind", "Upright"}, DefaultValue=0},
		{Key="UnlimitedReferenceBookSlot", DisplayName="Unlock Reference Book Slots", Description="Unlock reference book slots.", SettingType="Toggle", DefaultValue=false},

		{Key="TaiwuChildGender", DisplayName="Taiwu Child Sex", Description="Sex of Taiwu's children.", SettingType="Dropdown", Options={ "Random", "Male", "Female"}, DefaultValue=0},
		{Key="WorldChildGender", DisplayName="Other Child Sex", Description="Sex of other characters' children.", SettingType="Dropdown", Options={ "Random", "Male", "Female"}, DefaultValue=0},
		{Key="RestoreAttainmentPerGrade", DisplayName="Improve Attainment Bonus", Description="Restore the attainment bonus cap to 270%.", SettingType="Toggle", DefaultValue=false},
		{Key="TaiwuChildQuickGrowAge", DisplayName="Village Children Grow to Age X", Description="In Taiwu Village, children grow one year older each month until age X. Set to 0 to disable.", SettingType="Slider", DefaultValue=0, MinValue=0, MaxValue=14},
		{Key="OtherChildQuickGrowAge", DisplayName="Outside Children Grow to Age X", Description="Outside Taiwu Village, children grow one year older each month until age X. Set to 0 to disable.", SettingType="Slider", DefaultValue=0, MinValue=0, MaxValue=14},
		{Key="OnlyExistBloodParents", DisplayName="Show Blood Parents", Description="The parent list will always contain blood parents. Only applies to Taiwu's children.", SettingType="Toggle", DefaultValue=false},
		{Key="BanAddStepChildren", DisplayName="No Stepchildren", Description="Disable adding stepchildren. Only applies to Taiwu.", SettingType="Toggle", DefaultValue=false},
		{Key="GrowAbilitiesWithLoopingNeigong", DisplayName="Internal Arts Raise Attributes", Description="Running internal arts such as Bright Lion Strength or Sunyue Method can increase attributes. It must be actively running in the lower-left slot, not merely equipped. Adds 1 point each month.", SettingType="Toggle", DefaultValue=false},
		{Key="GrowQualificationsWithReadingBook", DisplayName="Grade-9 Books Raise Aptitude", Description="Reading grade-9 books can increase the corresponding aptitude by 1 point each month.", SettingType="Toggle", DefaultValue=false},
		{Key="AllowAllGenderInOrganization", DisplayName="All Sexes in Sects", Description="Any sect can have both men and women, without affecting promotion.", SettingType="Toggle", DefaultValue=false},
		{Key="LockDaysInMonth", DisplayName="Lock Time", Description="When enabled, time only decreases through active spending.", SettingType="Toggle", DefaultValue=false},
		{Key="MarryAdventrueIgnoreMarried", DisplayName="Marriage Adventures Ignore Marriage", Description="Marriage adventures ignore existing marriages.", SettingType="Toggle", DefaultValue=false},
		{Key="BanFavorDebt", DisplayName="No Favor Debt", Description="Prevent new favor debt from being created. Existing favor debt cannot be removed by this setting.", SettingType="Toggle", DefaultValue=false},
		{Key="RemoveSupportCost", DisplayName="Remove Some Support Costs", Description="Remove local favor and experience costs, but the requirements must still be met.", SettingType="Toggle", DefaultValue=false},
		{Key="SeverAndDivorce", DisplayName="Betrayal Divorce", Description="Sever the relationship and divorce at the same time, if married.", SettingType="Toggle", DefaultValue=false},
		{Key="MakeItemImmediately", DisplayName="Instant Item Crafting", Description="Craft items instantly.", SettingType="Toggle", DefaultValue=false},

	}

}